# Generated by Django 4.0 on 2021-12-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='vimeo_id',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
